---
language: python
services: docker
env:
  global:
    - ROLE_NAME: repo-ius
install:
  - pip install molecule yamllint ansible-lint docker
before_script:
  - cd ../
  - git clone --depth=1 https://github.com/wate/ansible-role-repo-epel.git repo-epel
  - mv ansible-role-$ROLE_NAME $ROLE_NAME
  - cd $ROLE_NAME
script:
  - molecule test
