---
language: python
services: docker
env:
  global:
    - ROLE_NAME: repo-ius
install:
  - pip install molecule yamllint ansible-lint docker
before_script:
  - cd ../
  - git clone --depth=1 https://github.com/wate/ansible-role-repo-epel.git repo-epel
  - mv ansible-role-$ROLE_NAME $ROLE_NAME
  - cd $ROLE_NAME
script:
  - molecule --version
  - ansible --version
  - ansible-lint --version
  - yamllint --version
  - molecule test
notifications:
  email: false
  slack:
    secure: pNMaQ8a0gYJNYlwSbd6dIkil4l6eZ+di3N7baN0F73frfIzDPQQWU7P/NV1eICnDkgsVFHZ8STTsEFPwF5hlFv4LW0HJaIKroEQUdsNRg8VbDINZigYl9Re1K3r2RaSfdxExxNt98v6nRJTyYJXYkJ5WBN8K20+yG0Lpjrc/SL3G12X7WI2Xy+D3fLNPrDrhjxVZaJx1JqkNKoNo1jQUul1g8b9x//v3lqogXCPKg52+5G6iApy1MyKntsD/1KH2yi9mDGg3ZhehkeBLNSYfsoKV+9oiAaTEhkrFGLKV8BSszaFL1WpKzjL6coABemB//4nUCRWguJDb2+PxoWkKPxfbPtyGYbfe8a9yPDQmoYlA5g+RAnj9CN5o5VNgii/r4p9ylQFAfOb8PqEM++1Hfm/sZNlZQKAY4XIqL2SUTnMarfcF0Ttt5Fx7NQ6iU+NRihUbDj6apKr5LG1XTOB3MN0DHapZ9jZGnzd8o/hegtUA1uqZCROdXTd6DryGHJwNBgF5DoM5Xe0TvyMOah7yA8/TOtT0SQuV+RLT0LNZssadMVO4vmJISHEs6yOL7J0b54ghDSBLJ3dxU0ORCLoF3UjvW8QGC0WDDZNUsLaOoSwGVcpWUuz+ox8+nl2CNvtb+ystzmY3gzMialiHxrvAERXDjpHKDJ5FkICoYfrGGiY=
