---
- name: install ius repo
  yum:
    name: https://repo.ius.io/ius-release-el{{ ansible_distribution_major_version }}.rpm
- name: change repository status
  ini_file:
    path: /etc/yum.repos.d/ius.repo
    section: ius
    option: enabled
    value: "{{ '1' if repo_ius_enabled else '0' }}"
